/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jp.visao;

import com.jp.modelos.Dicionario;
import com.jp.modelos.Lista;
import com.jp.modelos.TipoDeBusca;
import com.jp.persistencia.DicionarioDao;
import com.jp.persistencia.IDicionarioDao;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    IDicionarioDao dicionarioDao = null;
    
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        dicionarioDao = new DicionarioDao();
        
        //dicionarioDao.gerarVetor();
        /*File dicionario = new File("./src/com/jp/dicionario").listFiles()[0];
        try {
            FileReader fr = new FileReader(dicionario);
            BufferedReader br = new BufferedReader(fr);
            
            String linha = "";
            Lista palavras = new Lista();
            int i = 0;
            while((linha = br.readLine()) != null){
                palavras.insereNoFim(linha.substring(0, linha.length()-1));
            }
            br.close(); 
            
            FileWriter fw = new FileWriter(dicionario);
            BufferedWriter bw = new BufferedWriter(fw);
            while(!palavras.estaVazia()){
                bw.write(palavras.removeNoInicio().toString() + "\n");
            }
            bw.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        */
        
        
    }
    
    public void setarIcone(boolean achou) {
        if(achou) jLabelAchou.setIcon(new ImageIcon("./src/com/jp/icones/V_20x20.png"));
        else jLabelAchou.setIcon(new ImageIcon("./src/com/jp/icones/X_20x20.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPalavra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonSequencial = new javax.swing.JButton();
        jButtonBinaria = new javax.swing.JButton();
        jButtonArvore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelMilisegundos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNanosegundos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelAchou = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trabalho sobre AVL");

        jTextFieldPalavra.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldPalavra.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Palavra");

        jButtonSequencial.setBackground(new java.awt.Color(204, 255, 204));
        jButtonSequencial.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButtonSequencial.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSequencial.setText("Busca Sequencial");
        jButtonSequencial.setFocusable(false);
        jButtonSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSequencialActionPerformed(evt);
            }
        });

        jButtonBinaria.setBackground(new java.awt.Color(204, 255, 204));
        jButtonBinaria.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButtonBinaria.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBinaria.setText("Busca Binária");
        jButtonBinaria.setFocusable(false);
        jButtonBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinariaActionPerformed(evt);
            }
        });

        jButtonArvore.setBackground(new java.awt.Color(204, 255, 204));
        jButtonArvore.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButtonArvore.setForeground(new java.awt.Color(0, 0, 0));
        jButtonArvore.setText("Busca em Árvore");
        jButtonArvore.setFocusable(false);
        jButtonArvore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArvoreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tempo em milisegundos:");

        jLabelMilisegundos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelMilisegundos.setForeground(new java.awt.Color(0, 204, 102));
        jLabelMilisegundos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tempo em nanosegundos:");

        jLabelNanosegundos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelNanosegundos.setForeground(new java.awt.Color(0, 204, 102));
        jLabelNanosegundos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Achou?");

        jLabelAchou.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMilisegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNanosegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldPalavra)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSequencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonArvore, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAchou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonSequencial)
                .addGap(18, 18, 18)
                .addComponent(jButtonBinaria)
                .addGap(18, 18, 18)
                .addComponent(jButtonArvore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAchou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMilisegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNanosegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSequencialActionPerformed
        // TODO add your handling code here:
        Dicionario dicionario = dicionarioDao.buscar(TipoDeBusca.SEQUENCIAL, jTextFieldPalavra.getText()); // Aqui o André deve devolver o dicionário contendo o tempo em milisegundos, em nanosegundos e se achou a palavra ou não
        jLabelMilisegundos.setText(dicionario.getTempoDeResposta_milisegundo() + " ms");
        jLabelNanosegundos.setText(dicionario.getTempoDeResposta_nanosegundo()+ " ns");
        setarIcone(dicionario.isAchou());
        
    }//GEN-LAST:event_jButtonSequencialActionPerformed

    private void jButtonBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinariaActionPerformed
        // TODO add your handling code here:
        Dicionario dicionario = dicionarioDao.buscar(TipoDeBusca.BINARIA, jTextFieldPalavra.getText());
        jLabelMilisegundos.setText(dicionario.getTempoDeResposta_milisegundo() + " ms");
        jLabelNanosegundos.setText(dicionario.getTempoDeResposta_nanosegundo()+ " ns");
        setarIcone(dicionario.isAchou());
    }//GEN-LAST:event_jButtonBinariaActionPerformed

    private void jButtonArvoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArvoreActionPerformed
        // TODO add your handling code here:
        Dicionario dicionario = dicionarioDao.buscar(TipoDeBusca.ARVORE, jTextFieldPalavra.getText());
        jLabelMilisegundos.setText(dicionario.getTempoDeResposta_milisegundo() + " ms");
        jLabelNanosegundos.setText(dicionario.getTempoDeResposta_nanosegundo()+ " ns");
        setarIcone(dicionario.isAchou());
    }//GEN-LAST:event_jButtonArvoreActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArvore;
    private javax.swing.JButton jButtonBinaria;
    private javax.swing.JButton jButtonSequencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAchou;
    private javax.swing.JLabel jLabelMilisegundos;
    private javax.swing.JLabel jLabelNanosegundos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPalavra;
    // End of variables declaration//GEN-END:variables
}
